Repository pyxem/orix, pull requests merged in 2021-09, with the labels that each got.

#223 Simplify the Rotation.from_euler() API
  CHANGELOG.rst
  orix/quaternion/rotation.py
Labels: documentation

#222 Move .scatter method up to Misorientation
  CHANGELOG.rst
  orix/quaternion/orientation.py
  orix/tests/test_orientation.py
Labels: enhancement

#221 Uniform sampling of orientation space using cubochoric coordinates
  CHANGELOG.rst
  doc/bibliography.bib
  doc/clustering_across_fundamental_region_boundaries.ipynb
  doc/conf.py
  doc/index.rst
  doc/uniform_sampling_of_orientation_space.ipynb
  orix/quaternion/_conversions.py
  orix/quaternion/orientation.py
  orix/quaternion/orientation_region.py
  orix/quaternion/rotation.py
  orix/sampling/SO3_sampling.py
  orix/sampling/_cubochoric_sampling.py
  orix/sampling/sample_generators.py
  orix/tests/quaternion/__init__.py
  orix/tests/quaternion/test_conversions.py
  orix/tests/quaternion/test_orientation.py
  orix/tests/quaternion/test_orientation_region.py
  orix/tests/quaternion/test_quaternion.py
  orix/tests/quaternion/test_rotation.py
  orix/tests/quaternion/test_symmetry.py
  orix/tests/quaternion/test_symmetry_data.py
  orix/tests/sampling/__init__.py
  orix/tests/sampling/test_cubochoric_sampling.py
  orix/tests/sampling/test_sampling.py
  setup.py
Labels: enhancement

#225 Add MANIFEST.in and Black PR checks, set black version to 21.8b0
  .github/workflows/build.yml
  .pre-commit-config.yaml
  MANIFEST.in
  orix/io/plugins/_h5ebsd.py
  orix/io/plugins/ang.py
  orix/io/plugins/bruker_h5ebsd.py
  orix/plot/stereographic_plot.py
  orix/quaternion/orientation.py
  orix/quaternion/orientation_region.py
  orix/quaternion/symmetry.py
  orix/tests/conftest.py
  orix/tests/io/test_ang.py
  orix/tests/io/test_emsoft_h5ebsd.py
  orix/tests/io/test_io.py
  orix/tests/quaternion/test_orientation.py
  orix/tests/quaternion/test_orientation_region.py
  orix/tests/quaternion/test_rotation.py
  orix/tests/quaternion/test_symmetry.py
  orix/tests/quaternion/test_symmetry_data.py
  orix/tests/test_crystal_map.py
  orix/tests/test_crystal_map_plot.py
  orix/tests/test_crystal_map_properties.py
  orix/tests/test_neoeuler.py
  orix/tests/test_object3d.py
  orix/tests/test_phase_list.py
  orix/tests/test_scalar.py
  orix/tests/test_stereographic_plot.py
  orix/vector/neo_euler.py
  orix/vector/vector3d.py
  setup.cfg
  setup.py
Labels: dev

#226 Bump version to v0.8.dev0 and add Paddy Harrison (@harripj) to credits
  doc/_static/style.css
  doc/conf.py
  orix/__init__.py
Labels: dev

#228 Deprecate Object3d.data_dim property in favour of Object3d.ndim
  CHANGELOG.rst
  doc/contributing.rst
  orix/_util.py
  orix/base/__init__.py
  orix/tests/test_object3d.py
  orix/tests/test_util.py
Labels: documentation, deprecation
