Repository pyxem/orix, pull requests merged in 2021-05, with the labels that each got.

#184 Add .ipynb to .gitignore and update contributing guide accordingly
  .gitignore
  doc/contributing.rst
Labels: documentation

#185 Add CrystalMap.plot(), use matplotlib-scalebar, add xmap notebook
  CHANGELOG.rst
  doc/crystal_map.ipynb
  doc/index.rst
  doc/reference.rst
  orix/crystal_map/crystal_map.py
  orix/plot/__init__.py
  orix/plot/crystal_map_plot.py
  orix/tests/test_crystal_map.py
  orix/tests/test_crystal_map_plot.py
  orix/vector/vector3d.py
  setup.py
Labels: documentation, enhancement

#177 Improving the performance of the samplings utils (see #175)
  orix/sampling/SO3_sampling.py
  orix/sampling/__init__.py
  orix/sampling/sample_generators.py
  orix/sampling/sampling_utils.py
  orix/tests/test_sampling.py
Labels: enhancement

#188 Add method to create empty CrystalMap of a given shape
  CHANGELOG.rst
  doc/reference.rst
  orix/crystal_map/__init__.py
  orix/crystal_map/crystal_map.py
  orix/io/plugins/ang.py
  orix/tests/conftest.py
  orix/tests/io/test_ang_plugin.py
  orix/tests/io/test_orix_plugin.py
  orix/tests/test_crystal_map.py
Labels: enhancement

#194 Preserve symmetry when creating misorientations or when inverting orientations
  CHANGELOG.rst
  orix/quaternion/orientation.py
  orix/tests/test_orientation.py
Labels: bug
