Repository pyxem/orix, pull requests merged in 2021-06, with the labels that each got.

#196 Efficient calculation of misorientation angles via a new Orientation.get_distance_matrix() supporting Dask
  CHANGELOG.rst
  doc/bibliography.bib
  doc/bibliography.rst
  doc/clustering_across_fundamental_region_boundaries.ipynb
  doc/clustering_orientations.ipynb
  doc/conf.py
  doc/index.rst
  doc/reference.rst
  orix/_util.py
  orix/quaternion/orientation.py
  orix/quaternion/quaternion.py
  orix/quaternion/rotation.py
  orix/tests/test_orientation.py
  orix/tests/test_quaternion.py
  orix/tests/test_util.py
  setup.py
Labels: discussion, documentation, enhancement

#200 Change Sphinx documentation theme to Furo
  doc/conf.py
  setup.py
Labels: documentation

#202 Add Orientation.scatter() method for simpler plotting in axis-angle and Rodrigues space
  CHANGELOG.rst
  doc/clustering_across_fundamental_region_boundaries.ipynb
  doc/clustering_orientations.ipynb
  doc/reference.rst
  orix/base/__init__.py
  orix/plot/rotation_plot.py
  orix/quaternion/orientation.py
  orix/quaternion/orientation_region.py
  orix/sampling/sample_generators.py
  orix/tests/test_object3d.py
  orix/tests/test_orientation.py
  orix/tests/test_rotation_plot.py
Labels: enhancement

#210 Add transpose method to all 3D classes
  CHANGELOG.rst
  doc/reference.rst
  orix/base/__init__.py
  orix/quaternion/orientation.py
  orix/tests/test_miller.py
  orix/tests/test_orientation.py
  orix/tests/test_vector3d.py
  orix/vector/miller.py
Labels: enhancement
