Repository pyxem/orix, pull requests merged in 2021-12, with the labels that each got.

#251 Replace use of set_symmetry() with map_into_symmetry_reduced_zone() in user guide
  doc/clustering_across_fundamental_region_boundaries.ipynb
  doc/clustering_orientations.ipynb
  doc/contributing.rst
  doc/crystal_map.ipynb
  doc/index.rst
  doc/uniform_sampling_of_orientation_space.ipynb
Labels: documentation

#253 Add new classmethods from_axes_angles() to Rotation and Orientation classes
  CHANGELOG.rst
  doc/reference.rst
  orix/quaternion/orientation.py
  orix/quaternion/quaternion.py
  orix/quaternion/rotation.py
  orix/tests/quaternion/test_orientation.py
  orix/tests/quaternion/test_rotation.py
Labels: enhancement, documentation

#252 Add symmetry arg to Orientation __init__ and override methods to maintain symmetry
  CHANGELOG.rst
  doc/clustering_across_fundamental_region_boundaries.ipynb
  doc/clustering_orientations.ipynb
  doc/contributing.rst
  doc/crystal_map.ipynb
  doc/uniform_sampling_of_orientation_space.ipynb
  orix/base/__init__.py
  orix/quaternion/orientation.py
  orix/tests/quaternion/test_orientation.py
Labels: enhancement

#257 Expand list of related projects in the docs
  doc/related_projects.rst
Labels: documentation

#234 Simple plotting of unit cells
  CHANGELOG.rst
  orix/plot/_util.py
  orix/plot/unit_cell_plot.py
  orix/quaternion/orientation.py
  orix/tests/plot/test_unit_cell_plot.py
Labels: enhancement, help-wanted

#258 Fix reading of point groups with "-" sign in EMsoft h5ebsd files
  CHANGELOG.rst
  orix/io/plugins/emsoft_h5ebsd.py
Labels: bug

#256 Don't round array values in CrystalMap.get_map_data() by default, change in CrystalMap.plot()
  CHANGELOG.rst
  orix/crystal_map/crystal_map.py
  orix/plot/crystal_map_plot.py
  orix/tests/plot/test_crystal_map_plot.py
  orix/tests/test_crystal_map.py
Labels: bug

#255 Ensure Rotation.to_euler() doesn't divide by zero to suppress warning
  orix/quaternion/rotation.py
  orix/tests/quaternion/test_rotation.py
Labels: bug

#201 Euler angle color key
  CHANGELOG.rst
  doc/crystal_map.ipynb
  doc/reference.rst
  orix/plot/__init__.py
  orix/plot/orientation_color_keys/__init__.py
  orix/plot/orientation_color_keys/euler_color_key.py
  orix/plot/rotation_plot.py
  orix/quaternion/orientation.py
  orix/quaternion/rotation.py
  orix/quaternion/symmetry.py
  orix/tests/conftest.py
  orix/tests/io/test_ang.py
  orix/tests/plot/test_orientation_color_keys.py
  orix/tests/quaternion/test_orientation.py
  orix/tests/quaternion/test_symmetry.py
Labels: enhancement

#259 Remove deprecated import convention "Krakow_Hielscher" in from_euler()
  CHANGELOG.rst
  orix/quaternion/rotation.py
  orix/tests/quaternion/test_rotation.py
Labels: deprecation

#260 Correct azimuthal angle within fundamental sectors (IPFs)
  orix/plot/direction_color_keys/_util.py
  orix/tests/plot/test_orientation_color_keys.py
Labels: bug

#261 Packaging commits (Changelog and release)
  CHANGELOG.rst
  orix/__init__.py
Labels: dev

#262 Bump version to 0.9.dev0 post 0.8.0 release
  orix/__init__.py
Labels: dev
