Repository pyxem/orix, pull requests merged in 2021-02, with the labels that each got.

#146 Add stereo plot
  orix/plot/__init__.py
  orix/plot/stereo_plot.py
  orix/projections/stereographic_projection.py
  orix/tests/test_crystal_map_plot.py
  orix/tests/test_projections.py
Labels: enhancement, status : wip

#152 Update documentation to use Jupyter notebooks, add contributing guide
  .gitignore
  CHANGELOG.rst
  doc/changelog.rst
  doc/conf.py
  doc/contributing.rst
  doc/index.rst
  doc/installation.rst
  doc/related_projects.rst
  doc/stereographic_projection.ipynb
  orix/__init__.py
  orix/plot/stereo_plot.py
  orix/projections/__init__.py
  setup.py
Labels: dev, documentation, enhancement

#154 Make stereographic plot extend Matplotlib projections, doc improvements
  CHANGELOG.rst
  doc/_static/style.css
  doc/conf.py
  doc/index.rst
  doc/reference.rst
  doc/stereographic_projection.ipynb
  orix/io/plugins/ang.py
  orix/plot/__init__.py
  orix/plot/_symmetry_marker.py
  orix/plot/stereo_plot.py
  orix/plot/stereographic_plot.py
  orix/projections/__init__.py
  orix/projections/stereographic.py
  orix/projections/stereographic_projection.py
  orix/tests/test_crystal_map_plot.py
  orix/tests/test_projections.py
  orix/tests/test_stereographic_plot.py
  orix/tests/test_stereographic_projection.py
  orix/tests/test_vector3d.py
  orix/vector/vector3d.py
Labels: enhancement

#157 Add PR template w/ description, progress, code snippet and review sections
  .github/pull_request_template.md
Labels: dev

#156 Rename Vector3d spherical coordinates to azimuth, polar, radial
  CHANGELOG.rst
  doc/stereographic_projection.ipynb
  orix/plot/_symmetry_marker.py
  orix/plot/stereographic_plot.py
  orix/projections/stereographic.py
  orix/tests/test_stereographic_plot.py
  orix/tests/test_stereographic_projection.py
  orix/tests/test_vector3d.py
  orix/vector/vector3d.py
Labels: enhancement
