Repository pyxem/orix, pull requests merged in 2022-04, with the labels that each got.

#303 Speed up `dot` and `dot_outer` by not calling `unique` for identical `Symmetry`
  CHANGELOG.rst
  orix/quaternion/orientation.py
  orix/quaternion/symmetry.py
  orix/tests/quaternion/test_symmetry.py
  orix/tests/test_miller.py
Labels: enhancement, dev

#313 Remove functions deprecated for removal in 0.9
  CHANGELOG.rst
  doc/reference.rst
  orix/base/__init__.py
  orix/quaternion/orientation.py
  orix/tests/quaternion/test_orientation.py
  orix/tests/test_object3d.py
Labels: dev

#314 Add misorientation clustering notebook
  CHANGELOG.rst
  doc/clustering_misorientations.ipynb
  doc/clustering_orientations.ipynb
  doc/index.rst
  orix/quaternion/symmetry.py
Labels: documentation

#321 Add Dask-based lazy computation of quaternion-vector outer product
  CHANGELOG.rst
  orix/quaternion/quaternion.py
  orix/tests/quaternion/test_quaternion.py
Labels: enhancement, status: needs review

#317 Add memory efficient alternative to Misorientation.distance() using Dask
  CHANGELOG.rst
  CONTRIBUTING.rst
  doc/clustering_misorientations.ipynb
  doc/conf.py
  doc/reference.rst
  orix/data/__init__.py
  orix/quaternion/orientation.py
  orix/tests/quaternion/test_orientation.py
  setup.py
Labels: enhancement, documentation, status: needs review
