Repository pyxem/orix, pull requests merged in 2022-03, with the labels that each got.

#304 Silence warnings when `convention` argument is not passed
  CHANGELOG.rst
  doc/reference.rst
  orix/_util.py
  orix/quaternion/orientation.py
  orix/quaternion/rotation.py
  orix/tests/quaternion/test_orientation.py
  orix/tests/quaternion/test_rotation.py
  orix/tests/test_util.py
Labels: deprecation

#301 Remove `orix.scalar` and `Scalar` class
  CHANGELOG.rst
  CONTRIBUTING.rst
  MANIFEST.in
  doc/clustering_across_fundamental_region_boundaries.ipynb
  doc/clustering_orientations.ipynb
  doc/contributing.rst
  doc/crystal_geometry.ipynb
  doc/crystal_map.ipynb
  doc/reference.rst
  orix/base/__init__.py
  orix/crystal_map/crystal_map.py
  orix/plot/_symmetry_marker.py
  orix/plot/crystal_map_plot.py
  orix/plot/direction_color_keys/_util.py
  orix/plot/inverse_pole_figure_plot.py
  orix/plot/stereographic_plot.py
  orix/projections/stereographic.py
  orix/quaternion/orientation.py
  orix/quaternion/orientation_region.py
  orix/quaternion/quaternion.py
  orix/quaternion/rotation.py
  orix/quaternion/symmetry.py
  orix/sampling/S2_sampling.py
  orix/sampling/sample_generators.py
  orix/scalar/__init__.py
  orix/tests/conftest.py
  orix/tests/plot/test_crystal_map_plot.py
  orix/tests/plot/test_stereographic_plot.py
  orix/tests/quaternion/test_orientation.py
  orix/tests/quaternion/test_quaternion.py
  orix/tests/quaternion/test_rotation.py
  orix/tests/test_axangle.py
  orix/tests/test_miller.py
  orix/tests/test_scalar.py
  orix/tests/test_stereographic_projection.py
  orix/tests/test_vector3d.py
  orix/vector/fundamental_sector.py
  orix/vector/miller.py
  orix/vector/neo_euler.py
  orix/vector/vector3d.py
Labels: dev, deprecation

#302 Add `Orientation.angle_with_outer()` which is based on `get_distance_matrix()`
  CHANGELOG.rst
  doc/reference.rst
  orix/quaternion/orientation.py
  orix/quaternion/rotation.py
  orix/tests/quaternion/test_orientation.py
  orix/tests/quaternion/test_rotation.py
Labels: enhancement

#305 Add equality operator to `Rotation` and `hash` to `Symmetry`
  CHANGELOG.rst
  orix/quaternion/orientation.py
  orix/quaternion/rotation.py
  orix/quaternion/symmetry.py
  orix/tests/quaternion/test_orientation.py
  orix/tests/quaternion/test_rotation.py
  orix/tests/quaternion/test_symmetry.py
Labels: enhancement, dev

#310 Add logo to README.rst
  README.rst
  doc/index.rst
Labels: documentation

#307 Add `Vector3d.scatter()` reproject onto hemisphere functionality
  CHANGELOG.rst
  doc/stereographic_projection.ipynb
  orix/plot/stereographic_plot.py
  orix/tests/test_vector3d.py
  orix/vector/vector3d.py
Labels: enhancement

#306 Add Symmetry plot method
  CHANGELOG.rst
  doc/conf.py
  doc/index.rst
  doc/point_groups.ipynb
  doc/reference.rst
  orix/quaternion/symmetry.py
  orix/tests/quaternion/test_symmetry.py
Labels: enhancement, documentation

#312 Fix writing property arrays in masked CrystalMap to .ang file
  CHANGELOG.rst
  orix/io/plugins/ang.py
  orix/tests/io/test_ang.py
Labels: bug
