Repository pyxem/orix, pull requests merged in 2022-09, with the labels that each got.

#382 Make custom Arrow3D compatible with Matplotlib 3.6
  CHANGELOG.rst
  orix/plot/_util.py
Labels: bug

#384 Add doc example showing how to add a stereographic plot zoomed inset
  examples/stereographic_projection/zoom_inset_region.py
Labels: documentation

#386 Main branch into develop post 0.10.0
  .zenodo.json
  CHANGELOG.rst
  RELEASE.rst
  doc/tutorials/clustering_across_fundamental_region_boundaries.ipynb
  doc/tutorials/clustering_orientations.ipynb
  doc/tutorials/point_groups.ipynb
  orix/__init__.py
  orix/quaternion/symmetry.py
  orix/tests/quaternion/test_symmetry.py
Labels: dev

#387 Updates to develop branch post 0.10.0
  .github/workflows/perhaps_make_a_tagged_release_draft.yml
  CHANGELOG.rst
  orix/__init__.py
  setup.py
Labels: dev

#394 Add `python_requires>=3.7` packaging metadata
  .zenodo.json
  orix/__init__.py
  setup.py
Labels: bug, dev

#393 Allow to pass c/color and s/sizes to StereographicPlot.scatter()
  CHANGELOG.rst
  orix/plot/stereographic_plot.py
  orix/tests/plot/test_stereographic_plot.py
Labels: bug

#392 Deprecate minimal/brittle "3D" functionality for crystal maps
  CHANGELOG.rst
  orix/_util.py
  orix/crystal_map/crystal_map.py
  orix/crystal_map/phase_list.py
  orix/io/__init__.py
  orix/io/plugins/orix_hdf5.py
  orix/plot/crystal_map_plot.py
  orix/tests/conftest.py
  orix/tests/io/test_ang.py
  orix/tests/io/test_io.py
  orix/tests/io/test_orix_hdf5.py
  orix/tests/plot/test_crystal_map_plot.py
  orix/tests/test_crystal_map.py
Labels: deprecation

#391 Fix indexing/slicing into sliced CrystalMap
  CHANGELOG.rst
  orix/crystal_map/crystal_map.py
  orix/tests/test_crystal_map.py
Labels: bug
