Repository pyxem/orix, pull requests merged in 2022-05, with the labels that each got.

#325 Add `lazy` parameter to `Quaternion` and `Rotation` `.outer()` for easy `Dask` computation
  CHANGELOG.rst
  orix/quaternion/quaternion.py
  orix/quaternion/rotation.py
  orix/tests/quaternion/test_quaternion.py
  orix/tests/quaternion/test_rotation.py
Labels: enhancement

#328 Set matplotlib backend in `build.yml` only, remove assignment in tests
  orix/plot/crystal_map_plot.py
  orix/quaternion/rotation.py
  orix/tests/plot/test_crystal_map_plot.py
  orix/tests/plot/test_stereographic_plot.py
  orix/tests/test_crystal_map.py
  setup.cfg
Labels: dev, tests

#322 Describe and simplify crystal reference frame, restructure user guide
  CHANGELOG.rst
  doc/bibliography.bib
  doc/clustering_across_fundamental_region_boundaries.ipynb
  doc/clustering_misorientations.ipynb
  doc/clustering_of_orientations.rst
  doc/clustering_orientations.ipynb
  doc/crystal_directions.ipynb
  doc/crystal_geometry.rst
  doc/crystal_map.ipynb
  doc/crystal_reference_frame.ipynb
  doc/crystallographic_maps.rst
  doc/index.rst
  doc/inverse_pole_figures.ipynb
  doc/orientations.rst
  doc/point_groups.ipynb
  doc/reference.rst
  doc/stereographic_projection.ipynb
  doc/uniform_sampling_of_orientation_space.ipynb
  doc/vectors.rst
  orix/crystal_map/phase_list.py
  orix/io/plugins/_h5ebsd.py
  orix/plot/stereographic_plot.py
  orix/tests/conftest.py
  orix/tests/plot/test_stereographic_plot.py
  orix/tests/test_miller.py
  orix/tests/test_phase_list.py
  orix/vector/miller.py
Labels: enhancement, documentation

#316 Check user guide notebooks stored with cell outputs regularly
  .github/workflows/python-publish.yml
  .github/workflows/test_documentation_notebooks.yml
  CONTRIBUTING.rst
  README.rst
  RELEASE.rst
  doc/clustering_orientations.ipynb
  doc/crystal_directions.ipynb
  doc/index.rst
  doc/point_groups.ipynb
Labels: dev, documentation

#329 Prepare 0.9.0rc1 release candidate
  .github/pull_request_template.md
  .zenodo.json
  CHANGELOG.rst
  CONTRIBUTING.rst
  README.rst
  RELEASE.rst
  doc/bibliography.bib
  doc/clustering_across_fundamental_region_boundaries.ipynb
  doc/clustering_misorientations.ipynb
  doc/clustering_orientations.ipynb
  doc/crystal_directions.ipynb
  doc/crystal_map.ipynb
  doc/crystal_reference_frame.ipynb
  doc/inverse_pole_figures.ipynb
  doc/point_groups.ipynb
  doc/related_projects.rst
  doc/stereographic_projection.ipynb
  doc/uniform_sampling_of_orientation_space.ipynb
  orix/__init__.py
Labels: dev, documentation

#331 Fix reST formatting in project description in source distribution
  .github/workflows/test_documentation_notebooks.yml
  README.rst
  setup.py
Labels: dev

#333 Remove restriction to upload to PyPI via action
  .github/workflows/python-publish.yml
Labels: dev

#336 Deprecate Misorientation.distance() in favour of get_distance_matrix()
  CHANGELOG.rst
  doc/clustering_misorientations.ipynb
  doc/conf.py
  orix/quaternion/orientation.py
  orix/tests/quaternion/test_orientation.py
Labels: deprecation

#341 Post 0.9.0 release updates
  .zenodo.json
  CHANGELOG.rst
  CONTRIBUTING.rst
  MANIFEST.in
  RELEASE.rst
  environment.yml
  orix/__init__.py
Labels: dev, documentation

#342 Prepare post release 0.9.0.post0
  CHANGELOG.rst
  orix/__init__.py
Labels: dev

#344 Change version from "0.9.0.post0" to "0.10.dev0"
  orix/__init__.py
Labels: dev

#347 Bump oldest supported Python version to 3.7
  .github/workflows/build.yml
  .pre-commit-config.yaml
  CHANGELOG.rst
  CONTRIBUTING.rst
  doc/installation.rst
  setup.py
Labels: dev, documentation

#350 Add `black` automatic formatting to Jupyter notebooks
  .github/workflows/build.yml
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  doc/clustering_across_fundamental_region_boundaries.ipynb
  doc/clustering_misorientations.ipynb
  doc/clustering_orientations.ipynb
  doc/crystal_directions.ipynb
  doc/crystal_map.ipynb
  doc/crystal_reference_frame.ipynb
  doc/point_groups.ipynb
  doc/stereographic_projection.ipynb
  doc/uniform_sampling_of_orientation_space.ipynb
  setup.py
Labels: dev, documentation

#334 Migrate S2 samplings from diffsims, add hexagonal sampling
  CHANGELOG.rst
  doc/bibliography.bib
  doc/reference.rst
  doc/s2_sampling.ipynb
  doc/vectors.rst
  orix/plot/direction_color_keys/direction_color_key_tsl.py
  orix/sampling/S2_sampling.py
  orix/sampling/__init__.py
  orix/sampling/_polyhedral_sampling.py
  orix/tests/sampling/test_s2_sampling.py
  orix/tests/sampling/test_sampling.py
  orix/vector/fundamental_sector.py
Labels: enhancement

#340 Add Pole Density Function (PDF) functionality to `Vector3d`
  CHANGELOG.rst
  doc/bibliography.bib
  doc/pole_density_function.ipynb
  doc/reference.rst
  doc/s2_sampling.ipynb
  doc/uniform_sampling_of_orientation_space.ipynb
  doc/vectors.rst
  orix/plot/orientation_color_keys/euler_color_key.py
  orix/plot/stereographic_plot.py
  orix/quaternion/rotation.py
  orix/sampling/S2_sampling.py
  orix/sampling/__init__.py
  orix/tests/plot/test_stereographic_plot.py
  orix/tests/sampling/test_s2_sampling.py
  orix/tests/test_vector3d.py
  orix/vector/spherical_region.py
  orix/vector/vector3d.py
Labels: enhancement
