Repository pyxem/orix, pull requests merged in 2022-02, with the labels that each got.

#274 Bump Black version
  .pre-commit-config.yaml
  orix/projections/stereographic.py
  orix/quaternion/_conversions.py
  orix/quaternion/orientation.py
  orix/quaternion/orientation_region.py
  orix/quaternion/quaternion.py
  orix/quaternion/rotation.py
  orix/quaternion/symmetry.py
  orix/scalar/__init__.py
  orix/tests/quaternion/test_orientation.py
  orix/tests/quaternion/test_orientation_region.py
  orix/tests/quaternion/test_quaternion.py
  orix/tests/quaternion/test_rotation.py
  orix/tests/quaternion/test_symmetry.py
  orix/tests/test_scalar.py
  orix/tests/test_vector3d.py
  orix/vector/miller.py
Labels: dev

#272 .unique() method of Rotation does not return correct indexing for inversion
  CHANGELOG.rst
  orix/quaternion/rotation.py
  orix/tests/quaternion/test_rotation.py
Labels: bug

#277 Fix misorientation calculation in Orientation methods angle_with(), dot() and dot_outer()
  CHANGELOG.rst
  orix/quaternion/orientation.py
  orix/tests/quaternion/test_orientation.py
Labels: bug

#279 Add figure kwargs to plot methods
  CHANGELOG.rst
  orix/plot/inverse_pole_figure_plot.py
  orix/plot/rotation_plot.py
  orix/quaternion/orientation.py
  orix/tests/quaternion/test_orientation.py
Labels: enhancement

#278 Improve handling of property arrays in .ang writer
  CHANGELOG.rst
  orix/crystal_map/crystal_map.py
  orix/io/plugins/ang.py
  orix/tests/io/test_ang.py
Labels: bug

#282 Set release version to 0.8.1 and update changelog title
  CHANGELOG.rst
  orix/__init__.py
Labels: dev

#283 Allow manual triggering of publish action
  .github/workflows/python-publish.yml
Labels: dev

#284 Post 0.8.1 release updates
  CHANGELOG.rst
  MANIFEST.in
  RELEASE.rst
  orix/__init__.py
Labels: dev

#288 Handle symmetry correctly in Miller.in_fundamental_sector()
  CHANGELOG.rst
  orix/tests/test_miller.py
  orix/vector/miller.py
  orix/vector/vector3d.py
Labels: bug

#285 Implement rounding consistently to 12 decimal places in orix, eg. in `unique()` functions
  CHANGELOG.rst
  orix/base/__init__.py
  orix/quaternion/rotation.py
  orix/sampling/S2_sampling.py
  orix/tests/sampling/test_s2_sampling.py
  orix/tests/test_miller.py
  orix/vector/miller.py
  orix/vector/vector3d.py
Labels: bug, dev

#281 Implement quaternion arithmetic from numpy-quaternion
  CHANGELOG.rst
  orix/quaternion/quaternion.py
  setup.py
Labels: discussion, dev

#289 Prepare 0.8.2 release
  CHANGELOG.rst
  orix/__init__.py
Labels: dev

#293 Post 0.8.2 release updates
  .github/workflows/python-publish.yml
  CHANGELOG.rst
  MANIFEST.in
  RELEASE.rst
  orix/__init__.py
  setup.py
Labels: dev
