Repository pyxem/orix, pull requests merged in 2023-05, with the labels that each got.

#445 Create vectors from path ends
  CHANGELOG.rst
  examples/rotations/README.txt
  examples/rotations/combine_rotations.py
  orix/plot/stereographic_plot.py
  orix/tests/plot/test_stereographic_plot.py
  orix/tests/test_vector3d.py
  orix/vector/vector3d.py
Labels: bug, enhancement, documentation

#443 Improve plotting of vector labels
  CHANGELOG.rst
  doc/tutorials/crystal_directions.ipynb
  doc/tutorials/stereographic_projection.ipynb
  examples/misorientations/misorientation_from_aligning_directions.py
  examples/orientations/orientation_from_aligning_directions.py
  examples/stereographic_projection/restrict_to_fundamental_sector.py
  examples/stereographic_projection/wulff_net.py
  orix/plot/__init__.py
  orix/plot/_util.py
  orix/plot/stereographic_plot.py
  orix/tests/plot/test_plotting_utilities.py
  orix/tests/plot/test_stereographic_plot.py
  orix/tests/test_vector3d.py
  orix/vector/vector3d.py
Labels: enhancement

#449 Splitting Misorientation and Orientation into seperate files
  orix/quaternion/misorientation.py
  orix/quaternion/orientation.py
Labels: dev
