Repository pyxem/orix, pull requests merged in 2024-04, with the labels that each got.

#478 Minor maintenance updates before 0.12.0 release
  .github/workflows/build.yml
  .gitignore
  CHANGELOG.rst
  doc/dev/building_writing_documentation.rst
  doc/dev/running_writing_tests.rst
  doc/dev/setting_up_development_installation.rst
  doc/tutorials/crystal_reference_frame.ipynb
  doc/tutorials/point_groups.ipynb
  doc/user/applications.rst
  doc/user/related_projects.rst
  examples/crystal_maps/create_empty_map.py
  examples/misorientations/misorientation_from_aligning_directions.py
  examples/orientations/orientation_from_aligning_directions.py
  examples/rotations/rotating_z_to_high_symmetry_directions.py
  examples/rotations/rotations_mapping_fundamental_sector.py
  examples/rotations/sampling_rotations.py
  examples/stereographic_projection/zoom_inset_region.py
  orix/__init__.py
  orix/crystal_map/crystal_map.py
  orix/sampling/__init__.py
  orix/sampling/sample_generators.py
  orix/tests/plot/test_stereographic_plot.py
  orix/tests/sampling/test_sampling.py
  readthedocs.yaml
  setup.py
Labels: dev

#485 Remove support for Python 3.7
  .github/workflows/build.yml
  CHANGELOG.rst
  doc/user/installation.rst
  setup.py
Labels: dev

#486 Update README to use status badge table, rephrase reference to MTEX
  README.rst
  doc/index.rst
Labels: dev

#488 Update develop branch after 0.12.0
  .zenodo.json
  CHANGELOG.rst
  RELEASE.rst
  orix/__init__.py
Labels: dev

#493 `ax2qu` does not raise anymore if last dimension is `1`
  .pre-commit-config.yaml
  CHANGELOG.rst
  RELEASE.rst
  orix/__init__.py
  orix/quaternion/_conversions.py
  orix/tests/quaternion/test_quaternion.py
Labels: bug

#491 Discrepancy between Phase.from_cif and Phase(structure)
  .zenodo.json
  CHANGELOG.rst
  orix/__init__.py
  orix/crystal_map/phase_list.py
  orix/tests/test_phase_list.py
Labels: bug

#496 Main into develop post 0.12.1
  .zenodo.json
  CHANGELOG.rst
  orix/__init__.py
  orix/crystal_map/phase_list.py
  orix/quaternion/_conversions.py
  orix/tests/quaternion/test_quaternion.py
  orix/tests/test_phase_list.py
Labels: dev

#495 0.12.1.post0: pin nbconvert to fix docs
  doc/Makefile
  orix/__init__.py
  readthedocs.yaml
  setup.py
Labels: dev, documentation

#497 Main into develop after 0.12.1.post0
  doc/Makefile
  readthedocs.yaml
  setup.py
Labels: dev
